### ISSUE TITLE
FAMC constraint questions

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#130]
The FamilySearch GEDCOM 7 spec says in [section 3.2.2](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#records):

> Events stored as facts within an INDI record may also have [FAMC](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#FAMC) or [ASSO](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#ASSO) tags to indicate families and individuals that participated in those events. For example, a [FAMC](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#FAMC) pointer subordinate to an adoption event indicates a relationship to family by adoption; biological parents can be shown by a [FAMC](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#FAMC) pointer subordinate to the birth event; the eulogist at a funeral can be shown by an [ASSO](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#ASSO) pointer subordinate to the burial event; and so on.

And of course a `SLGC` can also have a subordinate `FAMC`.

**Question 1:** is it required or not required that any such `FAMC` in a `SLGC`, `BIRT`, `CHR`, or `ADOP` point to a family that also has a `FAMC` directly under the `INDIVIDUAL_RECORD` for the same family?  I.e., is it permissible to have the former without the latter?

a. 
```
    1 ADOP Y
    2 FAMC @F1@
```
b. 
```
    1 FAMC @F1@
```

**Question 2:** is it required or not required that if there is `FAMC.PEDI SEALING` then there must be a corresponding `SLGC.FAMC` for that family?

a.
````
    1 FAMC @F1@
    2 PEDI SEALING
````

b.
```
    1 SLGC
    2 FAMC @F1@
```

**Question 3:** is it required or not required that if there is `FAMC.PEDI ADOPTED` then there must be an `ADOP.FAMC` for that family?

a.
```
    1 FAMC @F1@
    2 PEDI ADOPTED
```

b.
```
    1 ADOP Y
    2 FAMC @F1@
```

For any of the above that are answered "not required", it seems that there can be interoperability problems, since (say) one implementation might use `FAMC.PEDI ADOPTED` and ignore `ADOP Y.FAMC`, whereas another implementation might use `ADOP Y.FAMC` and ignore `FAMC.PEDI ADOPTED` and hence they cannot exchange data without loss, even though they can both represent that information.

**Comment by tychonievich** [comment]
**Question 1**: reworded, can a person be adopted into a family, sealed into a family, or born into a family but not be a member of that family?\
**My answer**: yes they can, for example in the case of a surrogacy (BIRT.FAMC that is not in the INDI) or the early church practice of "adoption" to famous people (SLGC.FAMC that is not in the INDI)

**Question 2**: reworded, can the relationship between a child and its parent be described as "sealing" without a sealing event?\
**My answer**: I can't think of a case for this, but am unsure if we should specify that it is prohibited.

**Question 3**: reworded, can the relationship between a child and its parent be described as "adopted" without an adoption event?\
**My answer**: I'd assume that such a case referred to a *de facto* adoption rather than a formal adoption, and thus allow it.

**Comment by tychonievich** [comment]
Discussed by steering committee 2022-04-05

INDI.FAMC (and its antisymmetric FAM.CHIL) suggest social or spiritual membership in a family.

INDI.[ADOP|SLGC|BIRT|CHR] is an event. It's FAMC is a detail about the event. We could have the event with a family relationship or without

INDI.FAMC.PEDI ADOPTED as worded implies only a social relationship, which may or may not have any associated adoption event. Similarly, INDI.ADOP discusses an adoption event but may or may not indicate adoption becomes the primary relationship time for the FAMC.

INDI.FAMC.PEDI SEALING as worded *always* implies a SLGC. It is unclear if we should *require* or merely *recommend* the SLGC being present. Because not all tools support these two (because not all programs are interested in supporting LDS ordinances), there may be import/export chains between tools that leave one without the other (in either direction) so requiring is not viable.

Conclusion: none of these items should be enforced. But we could add a "recommended" text on the PEDI SEALING entry. All of this discussion might also fit in the technical FAQ, and/or expository notes in the spec.
