### ISSUE TITLE
Multiple surnames

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#136]
Spanish and Portuguese cultures have two surnames - one from each parent.

These are two independent surnames, not one "double-barrelled" surname, as is common in many English-speaking countries.

These two surnames may sometimes be separated by a particle/conjunction.  An example from [wikipedia](https://en.wikipedia.org/wiki/Spanish_naming_customs#Nominal_conjunctions):

`Óscar Arnulfo Romero y Galdámez`

> The character U+002F ( / , slash or solidus) has special meaning in a personal name, be‐
ing used to delimit the portion of the name that most closely matches the concept of a
surname, family name, or the like.

Since we have two surnames that are independent (and may not be consecutive) my application uses slashes around each of them.

```
1 NAME Óscar Arnulfo /Romero/ y /Galdámez/
2 GIVN Óscar Arnulfo
2 SURN Romero, Galdámez
```

Is the use of multiple slash-delimited surnames valid in GEDCOM 7.0?

If yes, I can create a PR to clarify the text - "portion of the name" => "portion (or portions) of the name".
If no, what would be the correct way to record such names

**Comment by dthaler** [comment]
I believe the current answer is No, but the GEDCOM 7 spec does have problems here.
[Section 2.8](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#personal-name) answers the question where it specifies:

```
NamePersonal = nameStr
             / [nameStr] "/" [nameStr] "/" [nameStr]

nameChar     = %x20-2E / %x30-10FFFF  ; any but '/' and '\t'
nameStr      = 1*nameChar
```

That production explicitly only allows a single "/" delimited portion.

A bug, in my view, is in the spec in the production of [PERSONAL_NAME_STRUCTURE](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#PERSONAL_NAME_STRUCTURE) where it has:

```
n NAME <PersonalName>                      {1:1}  [g7:INDI-NAME](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#INDI-NAME)
  +1 TYPE <[Enum](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb17-1)>                           {0:1}  [g7:NAME-TYPE](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NAME-TYPE)
     +2 PHRASE <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                      {0:1}  [g7:PHRASE](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#PHRASE)
  +1 <<[PERSONAL_NAME_PIECES](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#PERSONAL_NAME_PIECES)>>              {0:1}
  +1 TRAN <PersonalName>                   {0:M}  [g7:NAME-TRAN](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NAME-TRAN)
     +2 LANG <[Language](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#language)>                    {1:1}  [g7:LANG](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#LANG)
     +2 <<[PERSONAL_NAME_PIECES](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#PERSONAL_NAME_PIECES)>>           {0:1}
  +1 <<[NOTE_STRUCTURE](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NOTE_STRUCTURE)>>                    {0:M}
  +1 <<[SOURCE_CITATION](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#SOURCE_CITATION)>>                   {0:M}
```
The bug being where I think `<PersonalName>` should be `<NamePersonal>` to match section 2.8.

But then it gets more confusing in the PERSONAL_NAME_PIECES production which has:

```
PERSONAL_NAME_PIECES :=
n NPFX <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:NPFX](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NPFX)
n GIVN <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:GIVN](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#GIVN)
n NICK <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:NICK](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NICK)
n SPFX <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:SPFX](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#SPFX)
n SURN <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:SURN](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#SURN)
n NSFX <[Text](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb15-2)>                              {0:M}  [g7:NSFX](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#NSFX)
```

> Optional isolated name parts; see [PERSONAL_NAME_STRUCTURE](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#PERSONAL_NAME_STRUCTURE) for more.
> 
> “Lt. Cmndr. Joseph Allen jr.” might be presented as
> 
> 1 NAME Lt. Cmndr. Joseph /Allen/ jr.
> 2 NPFX Lt. Cmndr.
> 2 GIVN Joseph
> 2 SURN Allen
> 2 NSFX jr.

So what's odd there is the use of `{0:M}` instead of `{0:1}` without explanation of when you might have multiple.   And when you have multiple SURN tags, it is silent on how that relates to the portion in //.

But I think you could have:

> 1 NAME Óscar Arnulfo /Romero y Galdámez/
> 2 GIVN Óscar Arnulfo
> 2 SURN Romero
> 2 SPFX y
> 2 SURN Galdámez

which might be the best you can do at present.   It would be helpful for the GEDCOM Steering Committee to fix the bug above, and also add test explaining the use of multiple name pieces.  E.g., should it be

> 2 GIVN Óscar Arnulfo

or

> 2 GIVN Óscar
> 2 GIVN Arnulfo

or are both equally acceptable?  Since the spec is ambiguous about whether order is relevant, if the second form is acceptable, I would expect that the spec would have to say that order is important for GIVN, just like order is important for the SURN and SPFX tags in the Romero y Galdámez example.

**Comment by tychonievich** [comment]
This is an inherited issue with 5.5.1 and earlier. Only one pair of slashes allowed. We discussed fixing it, but if we want to make a backwards-incompatible change we have a number of other issues we want to resolve too, so we did not do so yet.

I believe the standard solution (as I've seen it in applications using 5.5.1 and earlier) is to use slashes for a substring including all family names and tag them individually in substructures, leaving joiners like `y` untagged.

```gedcom
1 NAME Óscar Arnulfo /Romero y Galdámez/
2 GIVN Óscar
2 GIVN Arnulfo
2 SURN Romero
2 SURN Galdámez
```gedcom

I also believe the standard solution on `GIVN` is to only combine them if they are used as a single name; for example, I work with someone named "Mary Lou"; that's one name with a space in it, always spoken together, not two separate names, and would be stored in one `GIVN` structure.

**Comment by tychonievich** [comment]
Discussed 2022-05-03
We mentioned many additional cases, including people with many family names. We also discussed that having *one* in slashes has some programmer utility when a name need to be shortened by a UI. We believe there is work to do on names, but do not think that a backwards-incompatible change to add multiple slashes is the right next step.

**Comment by dthaler** [comment]
10 MAY 2022 discussion: would be useful to add a clarifying note with the point about "only combine them if they are used as a single name" though this is more guidance for humans, not programmatically enforceable.

**Comment by albertemmerich** [comment]
The example shown by Luther is *not* 5.5.1! In 5.5.1 the PERSONAL_NAME_PIECES were defined as {0:1}!
PERSONAL_NAME_PIECES:=
n NPFX <NAME_PIECE_PREFIX> {0:1} p.55
n GIVN <NAME_PIECE_GIVEN> {0:1} p.55
n NICK <NAME_PIECE_NICKNAME> {0:1} p.55
n SPFX <NAME_PIECE_SURNAME_PREFIX {0:1} p.56
n SURN <NAME_PIECE_SURNAME> {0:1} p.55
n NSFX <NAME_PIECE_SUFFIX> {0:1} p.55
n <<NOTE_STRUCTURE>> {0:M} p.37
n <<SOURCE_CITATION>> {0:M} p.39

So GEDCOM 7.0 has modified this. To be honest I did not see any discussion to do this modification, and so far I was not prepared to follow the {1:M} in my application.

I do remember that we discussed to omit the comma separating of given names which was in spec 5.5.1, but was not used in most applications.

Now with the the new definition of
n GIVN <Text> {0:M}
we have new ambiguity whether to use
2 GIVN Mary Ann
or to use
2 GIVN Mary
2 GIVN Ann

There is no example in the standard for the case with more than one given name!

**Comment by dthaler** [comment]
I agree with Albert.  No rationale or example is given in the GEDCOM 7 spec for changing them to {0:M} and applications never supported this before.  Furthermore, I missed this when creating the maximal70.ged file which only has 1 of each.  So either the spec should be updated to state that applications need not support more than 1 and revert to {0:1} in future versions of the spec, or else we need to add the rationale and one or more examples to the spec, and add cases to maximal70.ged.

**Comment by tychonievich** [comment]
A little history here:

- The 7.0 design team discussed names and planned a model using a list of name parts instead of 5.5.1's slash-delimited datatype and optional substructures.
- Feedback on a beta draft suggested that was too large a change for some implementers, so we rolled it back.
- In the roll-back, we discussed the features the part-oriented model had that we could keep. The only one that made the cut was identifying single names with spaces by adding {0:M} cardinality to various name parts.

**Comment by tychonievich** [comment]
Short term: let's roll this back to 5.5.1 as an ambiguity in the 7.0 spec.
Long term: let's make a better way of storing names

**Comment by dthaler** [comment]
Discussion 17 MAY 2022: Since no implementations are believed to support it (and seems unlikely) and there is an ambiguity in the spec, propose removing {0:M} and going back to {0:1} in a patch.   This will not resolve the issue, just resolve the ambiguity.

From the *Guide to Version Numbers* in the current spec: "If there is an ambiguity or contradiction in the specification, it will be resolved in a patch version unless it is known that implementations interpreted the spec differently and that clarifying the intended meaning would cause incompatibilities between those implementations." I believe we can argue that this case is covered here (an ambiguity in spec with no contrary implementations)

**Comment by dthaler** [comment]
Discussion 31 MAY 2022: The GEDCOM Steering Committee believes that the question has been answered and along with the PR #143 merged above, this issue is complete.  @fisharebest please reactivate if there is anything we missed.

**Comment by fisharebest** [comment]
The definition for `SURN` says:

> A family name passed on or used by members of a family.

"A family name" implies **just one** family name.

So, for individuals with two family names, we can only have one `SURN` field, and it can only contain one family name...

**Comment by Norwegian-Sardines** [comment]
Individuals can have more than two “family” names in some cases and the SURN tag should either allow for comma delimited surname values as described in v5.5.1 or allow for multiple SURN tags to allow for indexing.

IMHO, too many times the GEDCOM Standard gets held back by trying to maintain a connection to application/programs that are still rooted in “modern western” naming understandings, rather than understanding the evolution of names.  People can have multiple surnames, no surname, gender based surnames, location based names, and various given name customs that need to be supported.
