### ISSUE TITLE
Allow RESN under other record types

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#158]
`SUBMITTER_RECORD` and `REPOSITORY_RECORD` can contain name and contact information (phone number, address, etc.).  Personal contact information may be private, such as an unlisted telephone number, and might be revealed in a submitter record or a repository record (for privately held sources such as a Family Bible, the person who holds the source may be entered as a repository). 

The `RESN` structure was defined to mark records as confidential or private, but in 7.0, `RESN` can only appear under `FAMILY_RECORD`, `INDIVIDUAL_RECORD`, or `MULTIMEDIA_RECORD`.

It may also be worth adding under `SOURCE_RECORD` since some GEDCOM files may put personal contact information in a source record, such as a private email address of someone else when citing email, or a private phone number when citing a phone interview.

**Comment by Norwegian-Sardines** [comment]
Since a Source_Record can also have TEXT associated with the record (defined as: "A verbatim copy of any description contained within the source.") and that text can include information that should be kept confidential, therefore instances of this record should also have RESN.  

The same could also be true of a information in the Note_Structure both "inline" and "shared" notes, where the data entry person could have notes to themselves that indicate something that should not be transferred our displayed to unauthorized individuals. This concept is not covered by RESN at the fact level since it is the NOTE not the Date/Place information that could be confidential!
