### ISSUE TITLE
CONT tag not explicitly defined

### ISSUE THREAD

**Issue by GPHemsley** [FamilySearch/GEDCOM#20]
Most mentions of the CONT tag in the 7.0.2 spec are in passing. It is not necessarily clear where CONT is allowed or how to parse it.

This the extent of the definition in 7.0.2:
> Line values cannot contain internal line terminators, but some payloads can. If a payload contains a line terminator, the payload is split on the line terminators into several payloads. The first of these split payloads is encoded as the line value of the structure’s line, and each subsequent split payload is encoded as the line value of a **line continuation** pseudo-structure of the structure. The tag of a line continuation pseudo-structure is `CONT`. The order of the line continuation pseudo-structures matches the order of the lines of text in the payload.
>
> Line continuation pseudo-structures are not considered to be structures nor to be part of a structure’s collection of substructures. They must appear immediately following the line whose payload they are encoding and before any other line.
>
> Because line terminators in payloads are encoded using line continuations, it is not possible to distinguish between U+000D and U+000A in payloads.

Note, in particular, that no ABNF is defined for the CONT tag, nor is the possible presence of CONT taken into account when defining other structures that may make use of it. Note also that the intended level of the CONT line is only implied by its use in examples.

**Comment by tychonievich** [comment]
Thanks for pointing this out. Does #22 adequately address this?

I should note that we never mention CONT when defining structures because CONT is a serialization artifact: CONT is how we escape line breaks inside payloads, just as `\n` is how we do that in C and `<br/>` is how we do that in HTML. The set of structures that can be followed by a CONT is exactly the set of structures that can have line breaks in their payloads; line breaks are a function of payload type, not of structure hierarchy. Should that note be added to the spec too?

**Comment by tychonievich** [comment]
Pull request discussed in 2021-07-13 steering committee meeting and approved as addressing the central part of this issue.
