### ISSUE TITLE
Empty strings in ABNF

### ISSUE THREAD

**Issue by DavidMStraub** [FamilySearch/GEDCOM#206]
Hi,

sorry in advance if this is a naive question. I've started looking into parsing GEDCOM 7 with Python and had some issues reading the `grammar.abnf` with the Python [abnf](https://github.com/declaresub/abnf) package. I traced it back to the presence of the empty string `""` as option in three cases.

- for `DateValue` and `DatePeriod`, `""` is given as last option. Could this be wrapped into `[` `]` as optional instead of having the empty string as option?
- For `listItem`, `""` is the first option. What is the motivation for that?

**Comment by tychonievich** [comment]
Empty strings as `""` instead of enclosing `[`...`]` were employed to make it clear to the reader that the empty string was a valid payload for those types. That's also why we included `""` as an option for DateValue even though it was also permitted for `DatePeriod`, one of `DateValue`'s options.

[RFC 5234](https://www.rfc-editor.org/rfc/rfc5234) does allow empty quoted strings, as given by the `*` instead of `1*` in the defining rule for `char-val`:

```abnf
char-val       =  DQUOTE *(%x20-21 / %x23-7E) DQUOTE
```

That said, in principle I see no objection to using optional notation instead, particularly if common tools fail to implement this part of ABNF: we can draw attention to the potential for an empty payload using a comment instead.

The `List:Text` payload type is used for `PLAC` and `PLAC.FORM`. `PLAC` is sometimes used with an empty payload supply its `MAP` and/or `EXID` substructures without providing a place name. We could argue about the necessity of that use (e.g. an empty `PLAC` payload could always be replaced by "`PLAC Earth`") but banning it now would violate semantic versioning.

**Comment by DavidMStraub** [comment]
Thanks @tychonievich!
