### ISSUE TITLE
FAMC.STAT PROVEN

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#225]
The GEDCOM7 spec says in defining g7:enumset-FAMC-STAT:

<html>
<body>

Value | Meaning
-- | --
CHALLENGED | Linking this child to this family is suspect, but the linkage has been neither proven nor disproven.
DISPROVEN | There has been a claim by some that this child belongs to this family, but the linkage has been disproven.
PROVEN | **There has been a claim by some that this child does not belong to this family**, but the linkage has been proven.

</body>
</html>

If the linkage has been proven but there has NOT been a claim by some that this child does not belong to this family, what value should be chosen?   The current wording of PROVEN disallows that status for this case.

**Comment by tychonievich** [comment]
My instinct is that this change is how people likely used `PROVEN`, but I will note that the requirement of a disputation has been present since this tag's introduction in 5.5.1 and there may be applications that use the disputation implication of `PROVEN` in their user interface. Thus, I worry that allowing unchallenged `PROVEN`s  might actually be a breaking change in a subtle but sometimes meaningful way.

**Comment by tychonievich** [comment]
Discussed 2022-10-18
We don't think `FAMC`.`STAT PROVEN` is much used, so changing it is probably OK. We want to check with a few other people before moving forward, though. If anyone reading this note knows of cases that use `FAMC`.`STAT PROVEN`, to mean there was a dispute or not, please let us know.

**Comment by Norwegian-Sardines** [comment]
Unless we are talking about DNA proof, relationships to a family are never truly “proven”, and that we can only base linkage on how good the existing evidence is. However, we can say that “proven” means that “strong evidence exits” that the family relationship exists.

I am reluctant to want to include the language that “their was a claim” that the connection was/is false because their may not be any controversy, rather that the connection has “strong evidence to be true”.   Maybe change the description to: “Strong evidence exists to indicate that the linkage to this family is correct.” 

If we can not agree to change the definition then a 4 option should be added with a definition that indicate that “strong evidence exists and is currently unchallenged”.

**Comment by tychonievich** [comment]
Proposed:
Add something like

> When these enumeration values were introduced it was assumed, but never specified, that "proven" referred to the definition provided by the [Board of Certification of Genealogists](https://www.familysearch.org/en/wiki/Genealogical_Proof_Standard). Because that meaning was not specified and other definitions of "proven" exist, existing files may use these values in other ways.
