### ISSUE TITLE
QUAY enum values are not tags

### ISSUE THREAD

**Issue by DavidMStraub** [FamilySearch/GEDCOM#229]
Hi,

while working on the [Python parser](https://github.com/DavidMStraub/python-gedcom7), I ran into a problem which I believe is an inconsistency in the current definition (or just a misunderstanding of mine).

The values of the `QUAY` enum (e.g. in the example file maximal70.ged) are integers. However the grammar defines `Enum = Tag` and `Tag` must start with an uppercase letter.

**Comment by dthaler** [comment]
I agree this is a bug in the 7.0 spec that did not exist in the 5.5.1 spec.
I think the correct fix is to change Enum to be
`Enum = Tag / Integer`
or even just minimally
`Enum = Tag / digit`

**Comment by fisharebest** [comment]
Might other/future Enums also want to be digits or integers?
This would rule out (3).

**Comment by tychonievich** [comment]
I like Option 1. I think it's the least disruptive fix.

**Comment by dthaler** [comment]
I would prefer option 1 more than allowing things like "2ND".   There's no demand for the permissiveness of "2ND" and it's not as good, in my view, as "2" or "SECOND", either of which are fine in option 1.   Since we can add permissiveness later, but can never remove permissiveness without a major version change, I'd argue for a less permissive fix now.
