### ISSUE TITLE
g7:SUBM-LANG

### ISSUE THREAD

**Issue by WGroleau** [FamilySearch/GEDCOM#266]
g7:SUBM-LANG allows multiple instances (and it should, since many genealogists are not monolingual).

1. Spec should clarify and/or recommend that they be listed in order of preference.
2. Might a subtag be useful for languages the submitter understands but is not fluent in?  Or an unambiguous fluency level? (I personally prefer CEFR over ACTFL or ILR but several countries define their own standards for measuring fluency.)

**Comment by WGroleau** [comment]
My SUBM currently has `1 LANG English Spanish Portuguese French` but that is not really compliant with 5.5.1 (and spelling out the language name is not complain with g7)  (Plus I'm actually better in Italian than French)

**Comment by tychonievich** [comment]
> Spec should clarify and/or recommend that they be listed in order of preference.

The spec currently says "The order of substructures of a single type indicates user preference, with the first substructure being the most-preferred value, unless a different meaning is explicitly indicated in the structure’s definition." I don't immediately see a need to call this one instance out specially

> Might a subtag be useful for languages the submitter understands but is not fluent in?

It is a set of preferred languages; it does not indicate why they prefer them (i.e. is not an assertion about submitter ability with that language, only that they prefer them). As this has been its meaning since the tag for several previous versions of the spec too, there are many files that use it and we cannot impose additional limitations on its meaning at this time.

> My SUBM currently has `1 LANG English Spanish Portuguese French`

Per the spec, this should be represented as

```gedcom
1 LANG en
1 LANG es
1 LANG pt
1 LANG fr
```

**Comment by tychonievich** [comment]
I think he comment above answers this question; if I missed something, please re-open this issue

**Comment by WGroleau** [comment]
The reason I put it the way I did is because my file and my application are still g5.5.1 but 5.5.1 assumed everyone is monolingual.  I did not propose changing the meaning; I proposed allowing a +1 tag to indicate level of fluency.  PHRASE would even work.

**Comment by tychonievich** [comment]
Ah, sorry I missed that part of the proposal. Do I understand the proposal to be something like the following?

```gedcom
0 @S1@ SUBM
1 LANG en
2 LEVEL CEFL C2
1 LANG ja
2 LEVEL ACTFL IM
2 LEVEL ILR 3
```

How do you envision applications using this information?

**Comment by WGroleau** [comment]
Yes, that would be one way.  I don't think an application could do anything with it, unless the payloads were limited to a few items defined in the spec.  But it could be displayed to a user to help them decide how best to contact the submitter or to better understand errors the submitter may have made in a particular language.  It should be optional, though, as many people have no knowledge of proficiency scales, or the SUBM record might be created by someone other than the person.

**Comment by dthaler** [comment]
I don't think there's a single definition of fluency.  Rather, fluency might vary by communication method, e.g., written vs. verbal might have very different levels of fluency (especially if one were deaf or blind).
