### ISSUE TITLE
1 CENS Y—Why?

### ISSUE THREAD

**Issue by WGroleau** [FamilySearch/GEDCOM#304]
5.5.1 did not give CENS a same line payload. G7 allows a Y

 I don't see the point in having a "1 CENS Y"  If I find the census, I'll include its details. If I don't find it, I don't know whether the INDI or FAM is listed and "1 CENS Y" would be dishonest.

**Comment by tychonievich** [comment]
The rule that some events could have Y and others not was confusing and a common cause for applications not obeying the 5.5.1 spec. In 7.0 we normalized this so that all events allow the Y payload.

As to where a `CENS Y`could come from, a diary entry or personal letter that says "a census taker came by today" would be one possible source of that.

**Comment by tychonievich** [comment]
Discussed in steering committee. We agree that this is rarely useful, but that changing it would make the spec more complicated to implement and would require a new major version (8.0).
