### ISSUE TITLE
Areas (OSM) in place hierarchy?

### ISSUE THREAD

**Issue by raipet** [FamilySearch/GEDCOM#340]
Is there a possibility to display in place hierarchy areas and not as LATI/LONG? And if yes, how?

As an example:
Hesse -> [nominatim.openstreetmap.org/ui/search.html?q=hessen](https://nominatim.openstreetmap.org/ui/search.html?q=hessen)

more infos about this topic in webtrees:
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/38223-areas-osm-in-place-hierarchy

**Comment by tychonievich** [comment]
In 7.0 if you have a URL you can do this with `EXID`, as for example

```gedcom
2 PLAC Hessen, Germany
3 EXID hessen
4 TYPE https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&class=boundary&osmid=
```

Note I used the durable OSMID <https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&class=boundary&osmid=62650> rather than the temporary search interface URL, but the search URL could also work.

7.0 does not have a way of storing the area bounds directly in the file, though such could be added by an application as an extension.

We could potentially add embedded area bounds information in 7.1, but it is not self-evident what that should look like. Area bonds have some nuance because the Lat/Lon are on a sphere and hence a non-linear coordinate system, leading to conflicting standards, with [KML](https://developers.google.com/kml/documentation/kml_tut) and [Shapefile](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf) as the two with the largest market share today. Both are relatively involved, and neither has a good way of storing either boundary uncertainty or changing boundaries over time, both of which are common in historical places. We've done a little discussion of what we might do to support those, possibly by working off of the [GEDCOM-L Addendum](https://genealogy.net/GEDCOM/)'s `_LOC` extension, but haven't yet proceeded to discussion of area boundaries.

**Comment by tychonievich** [comment]
Discussed in steering committee

In addition to the OSM authority and _LOC extension, FamilySearch has a place authority which has time but not boundaries. See <https://www.familysearch.org/en/wiki/FamilySearch_Places> for more. We have a defined EXID.TYPE for it (https://gedcom.io/exid-type/FamilySearch-PlaceId) if you want to use it instead of OSM so you can include a time window in the definition. You can also use both authorities as two separate EXIDs for the same place.

We do not have any current plans to include place boundaries in GEDCOM itself. If a GEDCOM extension does include it, we may revisit that to make that extension standard.
