### ISSUE TITLE
Mutual pointers

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM#342]
In the spec it states:

> A SOURCE_RECORD (p.45) may contain a pointer to a SHARED_NOTE_RECORD (p.43) and
vice versa. Applications must not create datasets where these mutual pointers form a
cycle. Applications should also ensure they can handle invalid files with such cycles in a
safe manner.

However, INDI and FAM records already point to each other (albeit with supplementary information), so I'm not sure why this warrants this warning.

From a data structures perspective, a warning is absolutely warranted in the case of a NOTE_STRUCTURE containing a SOURCE_CITATION containing a NOTE_STRUCTURE...and so on. But these are pointers, so there shouldn't be an issue.

**Comment by tychonievich** [comment]
This restriction was added because of semantics, not data traversal. SNOTE/SOUR mutual pointers would mean that the source of the note is the source the note is about, which doesn't make sense.

Conversely, the INDI/FAM mutual pointers have distinct semantics in each direction, creating doubly-linked edges instead of semantic cycles
