### ISSUE TITLE
PHRASE for SOURCE_REPOSITORY_CITATION

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM#343]
For pointers to INDI records the pointer can be VOID and the individual can be described in the PHRASE payload (e.g. INDI.ASSO.PHRASE).

Similarly, for SOURCE_CITATIONs the pointer can be VOID and the source is described in the PAGE payload.

For SOURCE_REPOSITORY_CITATION, the pointer can presumably be VOID, in which case would it be expected that the repository would be described in a NOTE? Is a PHRASE needed?

**Comment by tychonievich** [comment]
Discussed in steering committee

There are cases for void pointers without PHRASEs, for example to handle removing private or sensitive information during export. Repositories could be sensitive if the repository has requested that its provision of the source not be made public.

However, we do see how adding a phrase could allow free-text description of a repository instead of creating a REPO record, but don't see a strong reason to do that. If you do not have enough information to create a REPO record, but do have some information about the repository, that information can be placed in a NOTE.

If there is a case we have not considered or this does not resolve your question, feel free to re-open this issue.
