### ISSUE TITLE
Are cross-reference identifiers optional

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#408]
Section 1.3 says:

> Each record to which other structures point must have a cross-reference identifier. A record to which no structures point may have a cross-reference identifier, but does not need to have one. A substructure or pseudo-structure must not have a cross-reference identifier.

However the gedstruct throughout the document contradicts this currently, since it has lines like this for each record:

```gedstruct
n @XREF:INDI@ INDI                  {1:1}  g7:record-INDI
```

Where the cross-reference identifier is not denoted as null being permitted.  To be consistent with the paragraph quoted, the gedstruct would need to be

```gedstruct
n [@XREF:INDI@|<NULL>] INDI         {1:1}  g7:record-INDI
```

As such, validators that check for conformance against the gedstruct disallow files without the cross-reference identifier.

The ambiguity is, between the paragraph or the gedstruct, which is correct and which is incorrect.

**Comment by tychonievich** [comment]
I don't think there is any ambiguity. Section 3.1 defines the gedstruct syntax and defines the xref in this part of the line template as indicating that an identifier *may* appear there, not that it *must* appear there. 

In particular, the line template is defined with five bullets, they first of which is

> An optional cross-reference template `@XREF:`tag`@`, meaning this structure may be pointed to by other structures.
>
> Structures that are not pointed to by other structures need not have a cross-reference identifier even if their line template has a cross-reference template.

The `Y|<NULL>` syntax is defined in the third bullet as of that same list as one of several payload descriptors, and is not relevant here.

**Comment by dthaler** [comment]
Section 3.1 says:
> Options are placed between brackets [ and ] and have choices separated by pipes |.

but 
```
n @XREF:INDI@ INDI                  {1:1}  g7:record-INDI
```
Does not show anything as an "option" or "choice".  5.5.1 is the same.  It has
```
gedcom_line:=
level + delim + [optional_xref_ID] + tag + [optional_line_value] + terminator
```
But each record either shows the xref_ID, or doesn't show the xref_ID (HEAD, TRLR), implying that the xref_ID is conditionally mandatory based on the record type.

I would prefer removing the text:
> Each record to which other structures point must have a cross-reference identifier. A record to which no structures point may have a cross-reference identifier, but does not need to have one.

But perhaps that cannot be done without a breaking change.  Keeping it though means the gedstruct appears contradictory since it has no `[]`.

**Comment by tychonievich** [comment]
As you note, changing cardinality markers to be required on records would be a breaking change, not permitted until 8.0 at the earliest. I don't immediately see why we would do that, but I also don't seem harm (beyond a few extra bytes per dataset) in doing it in the next major version.

Changing the gedstruct syntax wouldn't be a breaking change to gedcom files, but it would break tools that use the machine-readable parts of the current spec. I also don't see why we would do it; if there's some ambiguity in how the current spec describes this syntax shouldn't we just find a clearer way to express its meaning, not change the syntax entirely?

Several comments in this thread seems to assume that the first bullet of the gedstruct definition is a rule applying to all forms of optionality instead of defining one part of a multi-part syntax. That suggests that there could be a better way of wording that first bullet. The proposed change to the syntax would not make the first bullet define all forms of optionality either, as section 3.1 of the current spec has five, not two, such forms, which for completeness I enumerate and quote below with the words introducing optionality in bold.

Optional line hierarchies (two forms):

1. **Options** are placed between brackets `[` and `]` and have choices separated by pipes `|`.

2. `{0:` means “optional” – the structure **may be omitted**

Optional cross reference identifiers:

3. An optional cross-reference template `@XREF:`tag`@`, meaning this structure may be pointed to by other structures.

    Structures that are not pointed to by other structures **need not have a cross-reference identifier** even if their line template has a cross-reference template.

Optional payloads (two forms):

4. `<`data type`>` means a non-pointer payload, as described in Data types. If the data type allows the empty string, the payload **may be omitted**.

5. `[`text`|<NULL>]` means the payload is **optional** but if present must be the given text.

(in hindsight the fifth case could have been made a "Maybe Y" datatype and merged with the fourth case, but changing that now seems likely to break tools that consume gedstructs so probably not worth doing)

The proposed `[@XREF:INDI@|<NULL>]` syntax would make three of these five cases use brackets. We could make it reduce the list from five to three cases overall (brackets, cardinality, and nullable datatypes), but to achieve that we'd need to

- define `<NULL>` as a construct in and of itself.
- change the specially-defined "`[`text`|<NULL>]`" into a specially-defined literal string option
- add constraints on the use of literal strings and brackets in payload descriptors to avoid at least the following undesirable cases:
    - optioned literals where enumeraton sets should be used, such as `+1 SEX [F|M|U|X]   {0:!}`
    - dynamic typing, such as `[<Age>|<DateValue>]` or `[@<XREF:INDI>@|<Text>]`
    - datatype extensions, such as `[unknown|<Age>]`
    - mandatory literals, such as `+1 AUTH Luther`
- add a requirement that cross-reference templates can only appear in an option list with a `<NULL>` option (required to be consistent with the normative text in section 1.3).

... and in the end we'd still have 3 cases, not 1, at the expense of what seems like a messier syntax description to me.

We could also get to the syntax from the first post in this issue by defining "`[@XREF:`tag`@|<NULL>]`" directly (like we currently do "`[`text`|<NULL>]`") instead of defining `<NULL>`, but its definition would be exactly the current definition of `@XREF:`tag`@` so I don't see what that gains us.

 

Since you mention 5.5.1 (which uses brackets and pipes more than 7.0 does, but still not in all cases were options exist), a little history of how this part of 7.0 came to be:

The 5.5.1 spec used parallel syntax to describe the "optional_line_value:= delim + line_value" and "optional_xref_ID:= xref_ID + delim". Some tools treated both the same as mandatory: an xref_ID was included if and only if the grammar said so, and so was the trailing delim that distinguished an empty-string line_value from a no-line_value line. Some treated them differently, omitting the optional_line_value entirely if the line_value was empty but always keeping the xref_ID. And some treated them the same the other way, omitting both when they had no (meaningful) content. When drafting 7.0 we considered all three cases and chose to handle the optional_line_value disagreements by separating the idea of a line value from the idea of a payload; and to handle the optional_xref_ID disagreements by picking the one that would work whether we decided to allow pointers to substructures or not (that decision came later in the 7.0 design process). I'm not sure I would make the same decision on either point if I were in that position again, but it's made now and can't be revisited until 8.0.

**Comment by dthaler** [comment]
Another point of ambiguity: HEADER and TRAILER are both defined like:
```
n HEAD                                     {1:1}  [g7:HEAD](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#HEAD)
```
Thus, if the xref id is optional, it's unclear whether it's optional or must-be-absent for HEAD and TRLR.
The more liberal interpretation would be that it's optional there too, say in case some extension contains a pointer to it.
But the counter argument is that the other types where it might be optional all show the xref in the gedstruct and these two don't, implying there is a syntactic difference.

**Comment by tychonievich** [comment]
The header and trailer are banned from having a cross-reference identifier both places the 7.0 spec describes such identifiers:

Section 1.3 defines them as pseudo-structures and requires that "a substructure or pseudo-structure must not have a cross-reference identifier."

Section 3.1 defines the cross-reference template that is defined as "meaning this structure may be pointed to by other structures" and does not give either of these pseudo-structures a cross-reference template.

Is there a third ambiguous place I am missing?

**Comment by dthaler** [comment]
Discussion 1/4/2024:
* Syntax is same as in 5.5.1, which didn't actually define the syntax in text.  7.0 text could perhaps be improved around the text
> An optional cross-reference template @XREF:tag@, meaning this structure may be pointed to by other structures.

> Structures that are not pointed to by other structures need not have a [cross-reference identifier](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#lines) even if their line template has a cross-reference template.
* Similar text appears twice (1.3 and 3.1) in the document.

**Comment by dthaler** [comment]
Closing since I've not been able to come up with any improved wording.
