### ISSUE TITLE
Add reference to GEDCOM 5.5 EL in version detection

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#45]
Spec: http://wiki-de.genealogy.net/Gedcom_5.5EL 
Detection (if I understand the spec properly): GEDC.VERS `5.5 EL` or GEDC.VERS `5.5EL`

**Comment by tychonievich** [comment]
We might also want an informative reference to the GEDCOM-L extension tags  that replace EL:
https://genealogy.net/GEDCOM/

**Comment by dthaler** [comment]
http://www.gaenovium.com/presentations/2014/Gaenovium%202014%20-%20Louis%20Kessler%20-%20Reading%20Wrong%20GEDCOM%20Right.pdf slide 38 says "To handle GEDCOM EL You have to handle its constructs in any file".

https://www.tamurajones.net/DetectingGEDCOM5.5EL.xhtml says "the addition of a space and EL to the version number is illegal, and the non-standard version number may prevent GEDCOM readers from recognising the file as a GEDCOM 5.5.1 file".  Part of the point, I gather, is that the EL extensions can be applied to multiple GEDCOM versions, and as such it is not itself a version and so isn't part of "version" detection per se.   Rather, it is an _extension_ and we could have a separate mechanism for extension detection.

I would say that each GEDCOM file is in a particular version, and uses one _or more_ extensions.   Often, such extensions are just a set of extension structures defined by the implementation and presumably specific to the HEAD.DEST value, if present, or the HEAD.SOUR value otherwise.

**Comment by dthaler** [comment]
@tychonievich Did PR #60 complete this issue, or are there are other changes needed?

**Comment by albertemmerich** [comment]
There are some problems with GEDCOM 5.5 EL:
* it is not valid GEDCOM 5.5. - it is not an extension following the rules of the standard. This is not only the illegal version number, but there are parts violating the GEDCOM standard (like multiple NAME.GIVN).
* it was replaced by the LOCATION RECORDS of GEDCOM-L team, and by this EL will not be used any more for other GEDCOM versions like 7.x

By this: We should not handle GEDCOM 5.5 EL as extension of GEDCOM 5.5.
It is a new version modifying GEDCOM 5.5. This was the main reason the GEDCOM-L group did not follow the concepts of 5.5 EL but established a 5.5.1 conforming ADDENDUM.

**Comment by clarkegj** [comment]
John Cardinal has written about proposed extensions in GEDCOM-5.5.2 which have not been officially adopted.
See https://jfcardinal.github.io/GEDCOM-5.5.2/extensions.html

I agree with Albert about not concerning ourselves with 5.5 EL.

Gordon

**Comment by dthaler** [comment]
Closing per discussion March 7, 2024
