### ISSUE TITLE
Confusing text around extension tags for non-structures

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#478]
Section 1.5.1 explains:
> Each use of the [extTag](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#lines) production is called an extension tag, including when used as a tag, calendar, month, epoch, or enumerated value.

But then it has the confusing sentence:
> The meaning of a documented extension tag is identified by its superstructure type and its URI, not its tag.

The term "superstructure" was defined in section 1.2 as something with a substructure:
> Every structure is either a record, meaning it is not contained in any other structure’s collection of substructures, or it is a substructure of exactly 1 other structure. The other structure is called its superstructure. Each substructure either refines the meaning of its superstructure, provides metadata about its superstructure, or introduces new data that is closely related to its superstructure.

But an extension tag used as a (say) enumerated value can be used with structure that is not a superstructure of anything.  So I believe it is incorrect as currently defined to refer to an enumerated value's "superstructure".

**Comment by tychonievich** [comment]
What should we say instead of superstructure?

- tag -- by superstructure, or none if a record
- calendar -- by being in the calendar part of a g7:type-date 
- month -- by the calendar it is used within
- epoch -- by the calendar it is used within
- enumerated value -- by the enumeration set it is used within, which in turn i determined by the containing structure type.

Possible revised wording:

- The meaning of a documented extension tag is identified by its URI, not its tag.
- The meaning of a documented extension tag is identified by the context in which it appears and its URI, not its tag.
- The meaning of a documented extension tag is identified by the context in which it appears: what datatype it is a part of, structure type it is a substructure of, or calendar it appears within.

**Comment by Norwegian-Sardines** [comment]
Personally, I believe that the definition at minimum must come from documented wording found in the URI that the creator of the extension has generated.  Without good documentation, the meaning of an extension can be misunderstood, and therefore misused.  The creator of the extension and therefore the documentation must include wording about its contextual use as well so as its use by other adopters can’t be misapplied to other structures outside of its intended use.  The extension tag itself can have little meaning when internationalized either because of term definition changes or the tag looking like one thing but meaning another.
