### ISSUE TITLE
Definition of PLAC

### ISSUE THREAD

**Issue by webtrees-pesz** [FamilySearch/GEDCOM#496]
It should be clearly defined what the lowest unit of jurisdiction is. Could a city district, a street, a building, a house be part of PLAC or is it part of ADDR? What about a hospital, a cemetery, a church?

**Comment by Norwegian-Sardines** [comment]
The software I use can map the PLAC tag up to and including addresses, buildings, hospitals, churches, cemeteries, and grave plots.

The definition of place should not restrict the type of place. A place is something that can be located on a map and be geographically located!

**Comment by webtrees-pesz** [comment]
Yes, the use of the word "jurisdiction" should be reconsidered and it should be described which content belongs in the PLAC tag and which in the ADDR tag.

Many programs handle the content of these tags differently, making data exchange more difficult.

**Comment by tychonievich** [comment]
Discussed in steering committee 2 JUL 2024

- We agree that "jurisdiction" is a term that some find confusing. However, we do not have a synonym we like better than jurisdiction.
- This term (and the format of the PLAC structure) dates back at least to the first standardized version of GEDCOM, 3.0, in 1987. In that spec, it had an additional description: "Place names consist of a string of one or more jurisdiction names, each separated from the other by a comma (a following space is optional), when each jurisdiction name is the name of a unit in a political, ecclesiastical, or geographical hierarchy."
- Because the current term goes back to 1987, we will leave it in place until the community has consensus on an alternative term to replace it with.
- We think that adding that "where each jurisdiction name is ..." text back to the 7.0 spec, possibly adding "social" to the list of unit types, will help clarify its meaning.
