### ISSUE TITLE
Documentation confusion about HEAD-SOUR-DATA

### ISSUE THREAD

**Issue by rhires** [FamilySearch/GEDCOM#549]
In the 7.0 doc version, 

> HEAD-SOUR-DATA 
> The electronic data source or digital repository from which this dataset was exported. The payload is the name of that source, with substructures providing additional details about the source (not the export).

However, the link that takes you there says this: 
> SOUR describes the originating software.
> CORP describes the corporation creating the software.
> HEAD.SOUR.DATA describes a larger database this data is extracted from.

HEAD.SOUR.DATA does not describe a larger database this data is extracted from. It's just a name of the data source or digital repository as per the linked-to-definition. The substructures don't really provide accurate or concise information about the software in question. I keep thinking the source data is the overall "where-the-data-itself" comes from, as in, the whole genealogy. 

In my case, HEAD.SOUR.DATA (to me), is the name of a book on rootsweb. Then I want to include the link to that book on rootsweb, the substructures don't seem to support that kind of thing. Which is why I'm confused. If I use "CORP", which is inconsistently defined (as I'm not a corporation), it gets even more confusing, because I'm copying someone's book, which is in HTML format, and converting it to GEDCOM - does that make me the CORP? Or is that the original author of the book?

CORP is defined: 
> CORP (Corporate name) g7:CORP
> The name of the business, corporation, or person that produced or commissioned the product.

Questions: 
What is "this data"? 

What is "the product"? And does this apply to the CORP creating the software? Is the product the software? Is it the book I'm transcribing?

HEAD.SOUR.DATA is not consistently defined. In both places, the appropriate definition would be to say: "The name of the source software" (though I think that DATA is a bad name for a name. Better would be to rename this particular tag or create a new one as HEAD.SOUR.SOFTWARE, with a substructure for +1 CORP (name of the entity that created it) (along with its substructure - changing CORP to ENTI (entity) might be a good thing, too, as it clears away some ambiguity about whether the creator is a corporation, business, or an individual/person), +1 NAME (name of the software itself), +1 DLOC (or WWW) download location), +1 EWEB (entity website, different from download location) to remain consistent with "ENTI")

So I'm rather confused. 

What I want to be able to do: 
- Say I'm the author of the gedcom itself, via a program that I myself wrote. 
- Say where I got the original data (its URL)
- Express the name of the book
- Give credit to the original author of the book

I realize this is about 3 things in one. 
1. Please update the docs to be more consistent. 
1. I've included some suggestions for new tags and ways to handle software and related websites.
1. Request help on the proper way to handle source and credit in the header of a gedcom. 

Thanks!

**Comment by rhires** [comment]
I think my overall concern about the header source data is that it's unclear what "data" refers to. Genealogical data or software data or even something else, like authorship data. 

What is the source of the overall gedcom? 
It's the software that created it, and the entity who put together the data so that the software could create the gedcom. 

Some software produced the file, so you want details about that, but some person put together the data that the gedcom is produced from, so you also want details about that person as well. And you want to be able to credit others. 

The header needs to have tags related to the software gedcom creation (what software created it, who created the software, their website, etc.) , and different tags related to the authorship of the gedcom (the person/entity that put together the data, and their information, as well as any source data (such as websites, or other gedcom authors) for the overall document. For example, I could produce a gedcom from 2 other gedcoms by different people and I would want to provide links and credit to these documents/authors. Or in my case, a rootsweb website where I got all the data and merely converted to a gedcom. I want to credit the original person who collated all that data.

**Comment by Norwegian-Sardines** [comment]
The HEAD section of the GEDCOM file provides information about the entire transmission.  Therefore the term “Source” in this context is about the source system of the transmission not the individual facts within transmission.  HEAD data refers to information about the transmission.

If you exported a copy of a GEDCOM from a website, then yes that website is the Source of the GEDCOM, but if you enter the same family information into a desktop program, then exported from the desktop program the Source of the GEDCOM would be the desktop software.

Every genealogy program implements its own dialect of GEDCOM, knowing the Source of the GEDCOM (i.e. who created the GEDCOM) maybe important to the receiving program!

**Comment by Norwegian-Sardines** [comment]
The person who put together the information is the SUBMitter.  There is a record for that too!

**Comment by dthaler** [comment]
GEDCOM Steering Committee discussion 24 SEP 2024:
* Regarding "HEAD.SOUR.DATA (to me), is the name of a book on rootsweb": This is not the intent, the book would be a `SOUR` record, not `HEAD`.`SOUR` since the book did not generate the GEDCOM file, nor did the program that generated the GEDCOM file automatically extract the data from that book (if there were, then it could indeed be HEAD.SOUR.DATA).  That is, the definition of `HEAD`.`SOUR` in the spec is "An identifier for the product producing this dataset..."
* When FamilySearch allowed downloads, the [header of the download said it was from Ancestral File](https://github.com/camhart/webapp/blob/master/uploads/hinckley.ged) using `SOUR`.`DATA`, and `SOUR`.`CORP` was the church:

```
1 SOUR ANSTFILE
2 VERS 4.19
2 DATA Ancestral File
3 DATE  5 JAN 1998
3 COPR Copyright (c) 1987, June 1998 by Intellectual Reserve, Inc.
4 CONT All Rights Reserved
```

* PAF looked like this, using `SOUR`.`NAME`, again with the church as `SOUR`.`CORP`:

```
1 SOUR PAF
2 NAME Personal Ancestral File
2 VERS 5.2.18.0
2 CORP The Church of Jesus Christ of Latter-day Saints
3 ADDR 50 East North Temple Street
4 CONT Salt Lake City, UT 84150
4 CONT USA
```

* `DATA` is used to identify a database (such as stored on CDs or an online database), whereas `NAME` is used to identify the application that created the GEDCOM file.
* Today all the uses of online databases we have found now use `NAME` to identify the website used to access the database.
* Typically `HEAD`.`SOUR`.`NAME` is now the long version of the short label used in `HEAD`.`SOUR`.
* "The electronic data source or digital repository from which this dataset was exported" and "HEAD.SOUR.DATA describes a larger database this data is extracted from" are intended to be synonymous and refer not to software but to a database aka digital repository.  We could change them to use the same wording.
* One option would be to deprecate `DATA` as no longer being in common use.

**Comment by rhires** [comment]
> > I realize this is about 3 things in one.
> > 
> > 1. Please update the docs to be more consistent.
> 
> I think we can use this issue to track this one, since this one would be potentially doable in 7.0.x.

Ok - I think that the response I got from @Norwegian-Sardines is a great way to update the documents for the things I asked for help and consistency on. His wording made things much more clear. 

I also would like clearer definitions of the concepts of "database" and "digital repository", as these can be confusing. 

I'm a programmer by trade, and my typical use of the word "database" is a relational database (such as SQL Server or SQLite), though I'm aware from my class on databases that the dictionary definition of "database" is anything that holds data. Maybe we could scrap "database" all together in favor of something more specific, such as "MEDIA", because then you can specify "physical book on paper" (such as a family Bible); digital book (in the form of a PDF), which could be found in a number of places, such as a given URL, or on CD; internet site, which can be broken down into http(s) and ftp; microfiche; and whatever else might be useful. 

"Digital Repository" that the GEDCOM was generated from - I guess that means the data in the GEDCOM is a subset of the larger dataset, so my family tree which has 2 branches, but comes from someone else's more comprehensive and complete tree. And where it comes from (the medium as I described above). 

I agree with your idea to use the same wording in both places and maybe an "upgrade" to the language while we're at it. I personally find it strange that an online database is not the same thing as the website that it's found on. For example, the NAME is "Family Search" but the URL would be https://familysearch.org/, or the name of the website is Family Search, but the "database" we're interested in (e.g., a GEDCOM file) might be Garcia family, because Family Search the website has multitudinous databases from which to choose. But here again, I get a bit confused, since I could use the URL to point at the specific "database" which combines the various things into one thing. I think the docs could spend a bit of time disentangling these concepts. 

> > 2. I've included some suggestions for new tags and ways to handle software and related websites.
> 
> This would be better separated into a separate issue in my opinion since new tags can only be added in 7.1 or later.

A new issue has been created for this. 
 
> > 3. Request help on the proper way to handle source and credit in the header of a gedcom.
> 
> The discussion comments on this issue are hopefully providing some help.

I definitely have a clearer understanding :-) 

Thanks!

**Comment by Norwegian-Sardines** [comment]
>I'm a programmer by trade, and my typical use of the word "database" is a relational database (such as SQL Server or SQLite), though I'm aware from my class on databases that the dictionary definition of "database" is anything that holds data.

I'm also a programmer and a database designer (have been since 1980, the term "database" is and will always be "anything that holds data".  A DBMS (Data Base Management System) manages the data, the database engine, and the database schema, allowing for data to be manipulated or extracted by users and other programs.  Applications Like DB2, IMS, DBASE, IDMS, SQLite, MySQL, Oracle Microsoft Access, etc are examples of a DBMS. 

Relational Databases are only one form of database, although very popular today, We can have "Network DB", Hierarchical DB, OODB, Keyed DB.

In GEDCOM v7 the `SOUR.DATA` field was defined as:
>The electronic data source or digital repository from which this dataset was exported. The payload is the name of that source, with substructures providing additional details about the source (not the export).

This definition does not use the term "database" but uses the term "electronic data source" or "digital repository", so if the GEDCOM payload was produced directly from an electronic book the name of this "book" could go here, but then the program that created the GEDCOM payload would also have to be specified in the `HEAD.SOUR`.  To my knowledge extracting data from an electronic book (that does not contain actual GEDCOM payload) is not currently being done, but could be done if the book was designed with that in mind!

**Comment by rhires** [comment]
I'm currently doing such a book extract, which is why my questions relate to that. I've had to markup the book by doing a lot of fixing b/c the original author used some rather basic HTML to list the data. In my markup, it's in a semi-csv format, and on top of that I've had to go through it line by line to rearrange some of the data, delete some things, regularize line endings, dates, fix formatting, etc., so that it can be properly parsed by a program I'm writing. It's been quite the intensive process. I have been using GED-inline to verify my GEDCOMs as they are produced by my program, but now that I've reached a point where it makes little sense to continue to modify the program, I have discovered that I still got some of it wrong because my import shows some missing connections. If you're interested I can send you the link to my github repo and the "book" I'm working with.

Anyway - I'm looking at https://gedcom.io/specifications/FamilySearchGEDCOMv7.html, which is v7.0.15, so there's that. I appreciate your deep experience with all things database :-) I think the definition you quoted is a good one. I was having issues with another definition that uses the term "database" to define the place that holds the data, whatever its form. My thought is to call the data-holder "media" since that seems to be a more descriptive term, but there may be issues with that as well.

**Comment by tychonievich** [comment]
Discussed in steering committee 1 OCT 2024

- We propose deprecating `HEAD`.`SOUR`.`DATA`, asking applications to use for `HEAD`.`DATA`.`NAME` instead, in our next patch (7.0.16).
- We also propose changing the two terms "database" and "digital repository" to use both terms separated with an "or" everywhere they appear to be internally consistent and not appear to be changing the term to restrict previously-permitted usage.
