### ISSUE TITLE
Using Gedcom file on website for users

### ISSUE THREAD

**Issue by islesihs** [FamilySearch/GEDCOM#58]
Anyone able to tell me how I get a gedcom file on a website for users to search with view only priveleges?
I am working with a historical society who would like to have this on the website.
Thank you.

**Comment by tychonievich** [comment]
The issues page of this site is for issues and feature requests on the GEDCOM standard itself. This question is more appropriate for the "general group" described at https://gedcom.io/community/

**Comment by clarkegj** [comment]
Upload your tree to genealogies.  The file will be preserved and only changeable by the submitter.
https://www.familysearch.org/tree/import/



From: islesihs ***@***.***>
Sent: Thursday, September 16, 2021 2:35 PM
To: FamilySearch/GEDCOM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FamilySearch/GEDCOM] Using Gedcom file on website for users (#58)


Anyone able to tell me how I get a gedcom file on a website for users to search with view only priveleges?
I am working with a historical society who would like to have this on the website.
Thank you.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFamilySearch%2FGEDCOM%2Fissues%2F58&data=04%7C01%7Cgordon%40familysearch.org%7C4bcf30478c3542dccb6808d9795182ec%7C61e6eeb35fd74aaaae3c61e8deb09b79%7C0%7C0%7C637674213270960232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bfljcLu36ZxeBZzka4YvBcFqrj1wIzgNo4dVloHq6%2B0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGMW7PEBIIYJIFT3IDZT5TUCJIIXANCNFSM5EFSAUVA&data=04%7C01%7Cgordon%40familysearch.org%7C4bcf30478c3542dccb6808d9795182ec%7C61e6eeb35fd74aaaae3c61e8deb09b79%7C0%7C0%7C637674213270970233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ys%2FFgkMKkmHH8kJ8CTZ%2BkcL6t7ySXJDc0q%2BaQAb4AQc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgordon%40familysearch.org%7C4bcf30478c3542dccb6808d9795182ec%7C61e6eeb35fd74aaaae3c61e8deb09b79%7C0%7C0%7C637674213270980227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OUZb7TYazs%2Bb%2FbyJ1LeZ4OyKOon9XZ5nwp5XS9HpnJE%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgordon%40familysearch.org%7C4bcf30478c3542dccb6808d9795182ec%7C61e6eeb35fd74aaaae3c61e8deb09b79%7C0%7C0%7C637674213270980227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VEwHQqRHn4Jy%2F8YB7hRWvHsFDttKyEvirNipUTzh0Ms%3D&reserved=0>.
