### ISSUE TITLE
Contradiction regarding DATE with no payload

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#81]
GEDCOM 7 has, in EVENT_DETAIL:

```
n DATE <DateValue> {0:1} g7:DATE
+1 TIME <Time> {0:1} g7:TIME
+1 PHRASE <Text> {0:1} g7:PHRASE
```

And `<DateValue>` requires minimally a year.  A `<NULL>` payload on DATE is not legal in the above syntax, since the spec says:

```
<datatype> means a non-pointer payload, as described in Data types (p.20).
If the datatype allows the empty string, the payload may be omitted.
[ text|<NULL>] means the payload is optional but if present must be the
given text.
```

However, the GEDCOM 7 spec also says:

> Date payloads may also be omitted entirely if no suitable form is known but a substructure
> (such as a PHRASE (p.74) or TIME (p.80)) is desired.

and

> Note — As defined by the grammar above, every date must have a year. If no year
> is known, the entire date may be omitted.
> Example — The following is an appropriate way to handle a missing year
> 2 DATE
> 3 PHRASE 5 January (year unknown)

So this appears to be a contradiction in the spec, and I think the EVENT_DETAIL needs to be corrected to say:

`n DATE [<DateValue>|<NULL>] {0:1} g7:DATE`

I suspect this contradiction is what led http://ged-inline.elasticbeanstalk.com/validate to report

`Invalid content for DATE tag: '' is not a valid <g7:DATE>`

for content like the example in the spec quoted above.

**Comment by tychonievich** [comment]
The passage you quote beginning "Date payloads may also be omitted entirely" is inside the section defining the Date datatype. I thus read this as saying the empty string is a valid `g7:type-Date`. Whether it is also a valid `g7:type-DatePeriod` or `g7:type-DateExact` is not clear to me, so we should definitely make that clearer.

It is not clear if it would be better to say 
```gedstruct
n DATE [<DateValue>|<NULL>] {0:1} g7:DATE
```
at the point of usage or
```abnf
DateValue   = "" / date / DatePeriod / dateRange / dateApprox
```
at the point of definition.

Points to decide:
1. Should clarify the use of empty strings in (a) the Datatype definition or (b) the using structure's definition?
2. Should empty strings be allowed for DatePeriod? (note that *all* DatePeriods allow a PHRASE)
3. Should empty strings be allowed for DateExact? (note that *no* DateExact allow a PHRASE, but all allow a TIME)

**Comment by albertemmerich** [comment]
I would like also to clarify whether we have to add a space after DATE when having the "" payload or not.
Line is defined:
Line = Level D [Xref D] Tag [D LineVal] EOL
So if we have no LineVal, we do not have the space.
If we have an empty LineVal, we have the space at the end of line.

Same problem we have with tags with payload [Y|Null]. If payload is Null (the normal case): Do we need the space?

**Comment by tychonievich** [comment]
[Section 1.2](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#structures) says

> Empty payloads and missing payloads are considered equivalent.

I read that to mean the space for an empty and/or missing payload is optional, neither required nor prohibited.

**Comment by dthaler** [comment]
Besides the `[Y|<NULL>]` case Albert mentions, an equivalent case is `EVEN <Text>` since `<Text>` is defined as `Text = *anychar` meaning 0 anychars is a legal Text payload.

**Comment by tychonievich** [comment]
Discussed dates 2021-11-09
- Do want to allow empty dates when there's a PHRASE.
- Prefer adding this to the spec more explicitly
- Prefer the `[<DateValue>|<NULL>]` syntax and will create a pull request for it

Discussed spaces 2021-11-09

- Considered `CHAN` which has no payload; preference for no trailing space, but unclear if that's recommended or required.
- Considered `EVEN` which as a text payload which could be empty; no clear preference emerged for if it should have a trailing space or not.
- Discussed that parsing should be liberal, but production should probably have a recommendation.

Deferred a decision on spaces to a later meeting.

**Comment by tychonievich** [comment]
Follow-up on dates:

The proposed change was a new `[<DateValue>|<NULL>]` syntax. In trying to implement this, I have several concerns:

1. If we do this, `<DateValue>` and `<DatePeriod>` vanish from the document, as they never appear without a `PHRASE` substructure
2. This requires extending the gedstruct metasyntax, making the specification more complicated and requiring new functionality of the automated tools that parse it (including those in the build/ directory of this repo, and those used by at least one third-party validator).
3. This implies that extensions may use DateValue and DatePeriod where the payload is required. That, in turn, means that an extension-compatible implementation has to keep track of two different versions of each datatype: the *nullable* DateValue and DatePeriod and the *required* DateValue and DatePeriod.

For these reasons, I would like us to revisit the alternative change of tweaking the ABNF:

```abnf
DateValue   = date / DatePeriod / dateRange / dateApprox / ""
DatePeriod  = %s"FROM" D date [D %s"TO" D date]
            / %s"TO" D date
            / ""
; rest of current Date ABF goes here
```

This will still allow only empty `DATE` if there's a substructure because of the universal rule

> A structure must have either a non-empty payload or at least 1 substructure.

But it keeps the syntax and intended semantics of the specification unchanged, prevents extensions from making their DateValue different than the ones in the standard, and does not require changes to existing specification-parsing tooling.

**Comment by tychonievich** [comment]
Discussed 2021-12-14: decided to go with the ABNF edit instead of the [<DateValue>|<NULL>] solution

**Comment by dthaler** [comment]
@tychonievich should this issue be closed now?
